const words=[
    {Rhyming1:["cat"," mat"," hat"," rat","bat","fat"]},
    {Rhyming2:["frog","dog","log",]},
    {Rhyming3:["bee","three","tree",]},
    {Rhyming4:["goat","boat","coat"]},
    {Rhyming5:["hug","jug","mug"]},
    {Rhyming6:["hen","men","pen"]},
    {Rhyming7:["cot","dot","hot"]},
    {Rhyming8:["jam","ham","ram"]},
    {Rhyming9:["cap","map","lap"]},
    {Rhyming10:["moon","spoon","cartoon"]},
    {Rhyming11:["win","tin","pin"]},
    {Rhyming12:["snake","rake","cake"]},
    {Rhyming13:["claw","paw","saw"]},
    {Rhyming14:["nut","hut","cut"]},
    {Rhyming15:["tag","rag","bag"]},
    {Rhyming16:["bear","pear","chair"]},
    {Rhyming17:["fan","man","van"]},
    {Rhyming18:["sock","rock","clock"]},
    {Rhyming19:["peg","leg","egg"]},
    {Rhyming20:["whale","snail","pail"]},
    {Rhyming21:["look","book","hook"]},
    {Rhyming22:["nest","vest","chest"]},
    {Rhyming23:["king","string","ring"]},
    {Rhyming24:["shoe","blue","glue"]},
    {Rhyming25:["mice","dice","rice"]},
    {Rhyming26:["lip","rip","dip"]},
    {Rhyming27:["sun","pun","run"]},
    {Rhyming28:["bell","well","shell"]},
    
]